### ISSUE TITLE
Ignoring the .o directory hurts its feelings

### ISSUE THREAD

**Issue by gulachek** [edquist/hyperfs#1]
The .o directory doesn't like being ignored. It wants to git to participate too. Maybe it could even win a participation trophy one day.

**Comment by edquist** [comment]
Hey @gulachek, we appreciate your emotional honesty.

We recommend running `git status` with the  `--ignored` option to view the files under the `.o` directory.  Of course, `git` does not actually pay attention to directories, only to the files contained in them, so technically the `.o` directory itself is never going to get any attention from `git`.  Sorry.
